### ISSUE TITLE
Website navigation issue for liboqs/algorithms

### ISSUE THREAD

**Issue by ghen2** [open-quantum-safe/www#227]
I spotted a navigation issue on the website, for page subtrees that "skip" a directory level, notably the [`liboqs/algorithms`](https://openquantumsafe.org/liboqs/algorithms/) section (which is divided into three separate directories `kem`, `sig`, and `sig_stfl`, but without their own index page).

The top row navigation link from any algorithm, eg. https://openquantumsafe.org/liboqs/algorithms/kem/ml-kem, back to the "algorithms" index page does not work: it refers to the page itself.  So for those pages, you can't (directly) navigate back to the parent.

For other pages, with an directly nested directory structure, those links work correctly.

**Comment by SWilson4** [comment]
Thanks for the report, @ghen2. I've opened #228 with a fix.
